version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kapje-vlan

  adminer:
    image: adminer:latest
    ports:
      - 8282:8080
    networks:
      - kapje-vlan

volumes:
  postgres-data:

networks:
  kapje-vlan:
    driver: bridge
